### ISSUE TITLE
Sigils for invalid @p's are displayed

### ISSUE THREAD

**Issue by rmariani** [urbit/sigil-js#24]
In http://sigil.tlon.io/. Entering `~mar`, for example, returns a sigil, even though `~mar` is not a valid `@p`. `mar` is a prefix, and only suffix phonemes can be galaxies. All illegal combinations (`~zodzod`, `~zodmar`) return sigils.

**Comment by vvisigoth** [comment]
lol stop
—
~poldec-tonteg
http://urbit.org

**Comment by rmariani** [comment]
what D:

**Comment by Fang-** [comment]
This is fine imo? We shouldn't restrict exploration of the sigil space.

(Other than that, unsure what needs to be stopped.)

**Comment by g-a-v-i-n** [comment]
Can someone verify if zodzod-zodzod is valid patp?

**Comment by bencalder** [comment]
~zodzod-zodzod isn't valid because `zod` isn't a valid prefix. However my understanding is that ~dozzod-dozzod is technically ~zod's full name.

**Comment by Fang-** [comment]
> However my understanding is that ~dozzod-dozzod is technically ~zod's full name.

_ackshually_, `@p` notation discards leading zeroes before rendering, so `~dozzod-dozzod` is not a valid `@p` representation. `0x0000.0000` just becomes `0x0` aka `~zod`.

This is also failing to accounts for planet scrambling/swizzling, ie:

```hoon
> `@ux`~doznec-dozzod
0xac45.8de2
```

All that said, `.~dozzod-dozzod` _is_ valid `@q` notation (and just resolves to `0x0`).

@g-a-v-i-n I still don't think sigil-js should really care about what it's being asked to render. In case you feel differently, [urbit-ob](https://github.com/urbit/ob-js/) implements validity checks in `isValidPatp` and `isValidPatq`, the latter of which just makes sure prefix and suffix syllables are in the right order/places.

**Comment by g-a-v-i-n** [comment]
I agree that its not worth implementing this check.
