### ISSUE TITLE
Sigils of prefixes hol and lar are identical

### ISSUE THREAD

**Issue by bencalder** [urbit/sigil-js#25]
The sigils of prefixes `hol` and `lar` are essentially identical (the components are just ordered differently).

`hol`'s sylgraph is [defined](https://github.com/urbit/sigil-js/blob/f7f29c5a4e2abc5207e7bd5f8dba8a0b3c18044d/src/lib/sylgraph.json) as `"hol":"7a365cc2:869bd8d8:2befa75a"`

`lar`'s is `"lar":"7a365cc2:2befa75a:869bd8d8"`

`hol` generated by [sigil.tlon.io](http://sigil.tlon.io/):
![hol](https://user-images.githubusercontent.com/263295/58058191-849ae800-7b2d-11e9-9137-c2301f18effd.png)

And `lar`:
![lar](https://user-images.githubusercontent.com/263295/58058192-849ae800-7b2d-11e9-81ab-8ce390159251.png)

I wrote a function to search for more matching pairs and didn't find any others.

**Comment by galenwp** [comment]
This guy with the collisions! Very good catch. Thanks.

@gavinpatkinson, what do you think? I could see one just getting rotated 90 degrees.

**Comment by gavinpatkinson** [comment]
This is a great catch! We should really validate these more comprehensively. I could rotate this but first I need to check if the rotation already exists.

**Comment by galenwp** [comment]
I'm not familiar with the internals of how sigils are generated — but it looks like the hashes Ben mentions above would be fairly easy to compare, no?

**Comment by gavinpatkinson** [comment]
the rotation value is included in the hash.  To make the hash, it is first a string like d.2.aaaa.270. Then it is hashed with murmur3 and converted to hexadecimal.

**Comment by bencalder** [comment]
Rotation won't help unless something else is added to the modified sigil. `par`, `har`, and `bar` are existing rotations of 45º, 90º, and 135º, respectively.

`par`
![par](https://user-images.githubusercontent.com/263295/58527250-93217900-8197-11e9-8efb-558ebd7f31a5.png)

`har`
![har](https://user-images.githubusercontent.com/263295/58527261-9e74a480-8197-11e9-86f2-051a02e19957.png)

`bar`
![bar](https://user-images.githubusercontent.com/263295/58527274-a46a8580-8197-11e9-97c7-beab60f2fbb8.png)

**Comment by galenwp** [comment]
They're all pokemon to me.

**Comment by vvisigoth** [comment]
@gavinpatkinson working on a Sigil v2 to address this and a few other display issues.
