### ISSUE TITLE
pour throws on lengthy point name

### ISSUE THREAD

**Issue by shrugs** [urbit/sigil-js#31]
I accidentally pasted a ticket (`~laprep-lartud-magnyl-bitbec`) into a field that was used as input for `pour#patp` and got a fun error:

```
bundle.js:10510 Uncaught TypeError: Cannot read property '0' of undefined
    at bundle.js:10510
    at Array.map (<anonymous>)
    at knoll (bundle.js:10508)
    at _pour (bundle.js:10480)
    at pour (bundle.js:10580)
    at Sigil (Sigil.js:6)
   // ... irrelevant frames removed
```

in the meantime I'm just going to throw this in a try-catch, but it should be documented whether or not this is expected behavior

**Comment by bencalder** [comment]
`~laprep-lartud-magnyl-bitbec` isn't a valid `@p`. AFAIK `pour()` will only accept values that pass `isValidPatp()` from [`ob-js`](`ob-js`)

**Comment by shrugs** [comment]
no of course it's invalid — we should either 1) document that the function should throw and/or 2) catch this specific error and throw something more readable than "can't read property '0' of undefined"

**Comment by bencalder** [comment]
Gotcha. The issue is entitled "lengthy point name", so I assumed you were expecting it to resolve to a valid point's sigil.

**Comment by shrugs** [comment]
ah, yeah — lengthy patp, then? are tickets patp or patq?

**Comment by bencalder** [comment]
Tickets are `patq`. [`urbit-key-generation`](https://github.com/urbit/urbit-key-generation)'s README mentions it

**Comment by shrugs** [comment]
hmm, that means I'm getting valid for `isValidPatp` on that ticket

```jsx
export default function InputSigil({
  className,
  patp,
  size,
  pass,
  error,
  focused,
  ...rest
}) {
  const colorway = selectColorway(pass, error, focused);
  const valid = ob.isValidPatp(patp);

  return valid ? (
    <Sigil patp={patp} size={size} colorway={colorway} margin={0} {...rest} />
  ) : (
    <AspectRatio aspectRatio={1} />
  );
}
```

otherwise it wouldn't try to render Sigil (which just calls `pour`)

**Comment by bencalder** [comment]
[:(](https://github.com/urbit/ob-js/issues/17)

**Comment by Fang-** [comment]
> `~laprep-lartud-magnyl-bitbec` isn't a valid `@p`

It certainly is a valid `@p`! But it's a moon, which Azimuth doesn't know about, and sigil-js doesn't presently support (and probably doesn't intend to).

Valid `@p`s are always valid `@q`s, but not all valid `@q`s are `@p`s (as strings).

**Comment by bencalder** [comment]
My mistake @shrugs, TIL `@p`'s valid namespace includes moons

**Comment by shrugs** [comment]
let's make pour throw on moon-and-greater points, then, since the max it supports is planet?

**Comment by Fang-** [comment]
That sounds fair, let's do it! (Though, I don't maintain this repo, so ultimately not my choice to make. (; )

**Comment by bencalder** [comment]
For now we could simply check `patp.length` just after the conversion to an array on [pour.js line 23](https://github.com/urbit/sigil-js/blob/master/src/lib/pour.js#L23). Or we could do something a little more in-depth. @Fang-, who's best to talk this through with? I'm happy to do the PR.

**Comment by Fang-** [comment]
Oh, this repo doesn't use ob-js... I guess a length-based check is fine then? Pretty sure @g-a-v-i-n's the boss around here.

**Comment by g-a-v-i-n** [comment]
pour isn't designed to render anything larger than planets at the moment.

**Comment by g-a-v-i-n** [comment]
It isn't that hard to add comet / moon support but it is very low priority. Happy to have a PR is anyone feels up to it. You'd have to modify the grid() function. The way the grid is generated now is sort of clunky because it uses a separate function definition that targets each row in the grid. The important thing is to preserve the small margin between each symbol.
