### ISSUE TITLE
Strokes leak outside of sigil box with margin: 0

### ISSUE THREAD

**Issue by Fang-** [urbit/sigil-js#35]
Passing a `margin: 0` results in details being drawn slightly outside of boundaries. In this example, on either side, but it probably happens for top and bottom too.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/3829764/61667350-0c41d600-acda-11e9-953c-4fdaadad44f4.png">

**Comment by g-a-v-i-n** [comment]
Well thats annoying. Not sure how big of a deal this is because sigils are normally rendered on a background that matches the stroke color. In most cases this should be invisible although I agree it isn't ideal.

**Comment by g-a-v-i-n** [comment]
Going to close this as I'm not sure there is a reasonable solution to this, and its not clear when this is an issue.

**Comment by Fang-** [comment]
It's also an issue for really small margins, but I guess you'd never want a margin smaller than the stroke size? Is the solution maybe to enforce that (or just draw a border around the sigil)?

**Comment by Fang-** [comment]
(A border in the same way that we already have "borders" between the quadrants.)
