### ISSUE TITLE
Incorrect stroke/spacing/sizing(?) around ~sun

### ISSUE THREAD

**Issue by Fang-** [urbit/sigil-js#53]
Observe this rendering of ~sovsun-lasrev:

![image](https://user-images.githubusercontent.com/3829764/107165305-c4190000-69b2-11eb-8a03-32b452db68b2.png)

Note how the top right quadrant ("sun") hugs very close to the top left, and the bottom right's background/stroke(?) is drawn on top of it.

**Comment by Fang-** [comment]
Similar issue with the strokes in the bottom left quadrant here bleeding over into the top left.

![image](https://user-images.githubusercontent.com/3829764/119832924-f10c0700-befe-11eb-9984-ea553d1543ba.png)

**Comment by g-a-v-i-n** [comment]
Hmmm....
